# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Get current date
      id: date
      run: echo "name=date::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
    - name: Build Linux Amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: |
        go build -ldflags " \
          -X github.com/nagylzs/gitlab-kanboard-gateway/internal/version.Built=${{ steps.date.outputs.date }} \
          -X github.com/nagylzs/gitlab-kanboard-gateway/internal/version.Commit=${COMMIT} \
          -X github.com/nagylzs/gitlab-kanboard-gateway/internal/version.Branch=${BRANCH}" \
          -o gitlab-kanboard-gateway \
          cmd/gitlab-kanboard-gateway/gitlab-kanboard-gateway.go

    - name: 'Upload Linux Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gitlab-kanboard-gateway-linux-amd64
        path: gitlab-kanboard-gateway
        retention-days: 5

    - name: Build Windows Amd64
      env:
        GOOS: windows
        GOARCH: amd64
      run: |
        go build -ldflags " \
          -X github.com/nagylzs/gitlab-kanboard-gateway/internal/version.Built=${{ steps.date.outputs.date }} \
          -X github.com/nagylzs/gitlab-kanboard-gateway/internal/version.Commit=${COMMIT} \
          -X github.com/nagylzs/gitlab-kanboard-gateway/internal/version.Branch=${BRANCH}" \
          -o gitlab-kanboard-gateway.exe \
          cmd/gitlab-kanboard-gateway/gitlab-kanboard-gateway.go

    - name: 'Upload Windows Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gitlab-kanboard-gateway-windows-amd64
        path: gitlab-kanboard-gateway.exe
        retention-days: 5